version: "3.3"

services:
    bootstrap:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        command: ./.docker/bootstrap.sh

    redis:
        image: redis:6.2.5-alpine
        expose:
            - 6379

    server:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        depends_on:
            - bootstrap
            - redis
        expose: 
          - "3000"
    
    nginx:
        image: nginx:1.21.1-alpine
        volumes:
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - server
        ports:
            - "3000:3000"

