version: "3.3"

services:
    bootstrap:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        command: ./.docker/bootstrap.sh

    redis:
        image: redis
        expose:
            - 6379

    server1:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        depends_on:
            - bootstrap
            - redis
        ports:
          - "3001:3000"
    
    server2:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        depends_on:
            - bootstrap
            - redis
        ports:
          - "3002:3000"
    
    # nginx:
    #     image: nginx:latest
    #     volumes:
    #         - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    #     depends_on:
    #         - server
    #     ports:
    #         - "3000:3000"

