version: "3.3"

services:
    bootstrap:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        command: ./.docker/bootstrap.sh

    server:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        depends_on:
            - bootstrap
        ports:
            - "3000:3000"
